export const infrastructureData = {
  resources: [
    {
      id: "i-0a1b2c3d4e5f6g7h8",
      name: "web-server-prod-1",
      type: "EC2",
      provider: "AWS",
      region: "us-east-1",
      status: "running",
      healthScore: 85,
      criticalIssues: 2,
      highIssues: 3,
      mediumIssues: 5,
      lowIssues: 1,
      complianceScore: 78,
      tags: { Environment: "Production", Team: "Platform" },
      lastScanned: "2024-01-15T10:30:00Z",
      owner: "platform-team@example.com",
    },
    {
      id: "i-1b2c3d4e5f6g7h8i9",
      name: "api-server-prod-1",
      type: "EC2",
      provider: "AWS",
      region: "us-east-1",
      status: "running",
      healthScore: 92,
      criticalIssues: 0,
      highIssues: 1,
      mediumIssues: 2,
      lowIssues: 0,
      complianceScore: 95,
      tags: { Environment: "Production", Team: "Backend" },
      lastScanned: "2024-01-15T10:32:00Z",
      owner: "backend-team@example.com",
    },
    {
      id: "i-2c3d4e5f6g7h8i9j0",
      name: "batch-processor-1",
      type: "EC2",
      provider: "AWS",
      region: "us-west-2",
      status: "running",
      healthScore: 88,
      criticalIssues: 1,
      highIssues: 2,
      mediumIssues: 3,
      lowIssues: 2,
      complianceScore: 82,
      tags: { Environment: "Production", Team: "Data" },
      lastScanned: "2024-01-15T10:28:00Z",
      owner: "data-team@example.com",
    },
    {
      id: "i-3d4e5f6g7h8i9j0k1",
      name: "staging-app-server",
      type: "EC2",
      provider: "AWS",
      region: "us-east-1",
      status: "running",
      healthScore: 75,
      criticalIssues: 3,
      highIssues: 4,
      mediumIssues: 6,
      lowIssues: 3,
      complianceScore: 70,
      tags: { Environment: "Staging", Team: "Platform" },
      lastScanned: "2024-01-15T10:25:00Z",
      owner: "platform-team@example.com",
    },
    {
      id: "rds-postgres-prod-main",
      name: "postgres-prod-primary",
      type: "RDS",
      provider: "AWS",
      region: "us-east-1",
      status: "running",
      healthScore: 90,
      criticalIssues: 0,
      highIssues: 1,
      mediumIssues: 1,
      lowIssues: 0,
      complianceScore: 93,
      tags: { Environment: "Production", Team: "Database" },
      lastScanned: "2024-01-15T10:35:00Z",
      owner: "dba-team@example.com",
    },
  ],
  stats: {
    avgHealthScore: 78,
    healthScoreTrend: -3,
    needAttention: 4,
    totalIssues: 40,
    criticalIssues: 6,
    averageScore: 89,
    averageScoreTrend: 25,
    lastScanTime: "2 min ago",
  },
  infrastructure: {
    containerClusters: 0,
    kubernetesWorkloads: 0,
    standaloneVMs: 4,
    vmScalingGroups: 0,
    relationalDatabases: 1,
    blockStorage: 0,
    fileStorage: 0,
    objectStorage: 0,
  },
  securityIssues: {
    critical: 6,
    high: 11,
    medium: 17,
    low: 6,
    totalIssues: 40,
    todayChange: 43,
    cveCount: 4,
    threatsCount: 20,
    zeroDayCount: 11,
    secretsCount: 4,
    complianceCount: 9,
  },
  complianceSystems: [
    {
      name: "Payment-Prod",
      healthScore: 88,
      criticalGaps: 12,
      controlsCount: 200,
      owner: "Alex Kim",
      tags: ["Prod", "PCI DSS v4.0"],
    },
    {
      name: "Health-Records",
      healthScore: 84,
      criticalGaps: 18,
      controlsCount: 188,
      owner: "Dr. Sarah Johnson",
      tags: ["Prod", "HIPAA 2023"],
    },
    {
      name: "Data-Pipeline",
      healthScore: 89,
      criticalGaps: 154,
      controlsCount: 154,
      owner: "Sarah Chen",
      tags: ["Prod", "SOC 2 Type II"],
    },
    {
      name: "Auth-Service",
      healthScore: 86,
      criticalGaps: 117,
      controlsCount: 117,
      owner: "Michael Torres",
      tags: ["Prod", "ISO 27001:2022"],
    },
  ],
}
