import type { SecurityFinding } from "./types"

// Demo security findings for fallback when backend returns empty
export const demoSecurityFindings: SecurityFinding[] = [
  {
    id: "finding-001",
    severity: "CRITICAL",
    title: "IAM Role with Excessive Permissions",
    resource: "SafeRemediate-Lambda-Remediation-Role",
    resourceType: "IAM Role",
    description: "This IAM role has 28 allowed actions but only uses 0 of them. 28 unused permissions should be removed to follow least privilege principle.",
    remediation: "Remove unused IAM permissions: iam:CreateUser, iam:DeleteUser, iam:AttachUserPolicy, and 25 others.",
    category: "IAM",
    discoveredAt: new Date().toISOString(),
    status: "open",
  },
  {
    id: "finding-002",
    severity: "HIGH",
    title: "S3 Bucket Without Encryption",
    resource: "app-logs-bucket-prod",
    resourceType: "S3 Bucket",
    description: "S3 bucket does not have server-side encryption enabled, potentially exposing sensitive data at rest.",
    remediation: "Enable SSE-S3 or SSE-KMS encryption on the bucket.",
    category: "S3",
    discoveredAt: new Date(Date.now() - 86400000).toISOString(),
    status: "open",
  },
  {
    id: "finding-003",
    severity: "HIGH",
    title: "Security Group Allows Unrestricted SSH",
    resource: "sg-0abc123def456",
    resourceType: "Security Group",
    description: "Security group allows SSH (port 22) access from 0.0.0.0/0, exposing instances to potential brute force attacks.",
    remediation: "Restrict SSH access to known IP ranges or use AWS Systems Manager Session Manager.",
    category: "EC2",
    discoveredAt: new Date(Date.now() - 172800000).toISOString(),
    status: "open",
  },
  {
    id: "finding-004",
    severity: "MEDIUM",
    title: "Lambda Function Without VPC Configuration",
    resource: "data-processor-lambda",
    resourceType: "Lambda Function",
    description: "Lambda function is not configured to run within a VPC, limiting network isolation options.",
    remediation: "Configure the Lambda function to run within a VPC with appropriate security groups.",
    category: "Lambda",
    discoveredAt: new Date(Date.now() - 259200000).toISOString(),
    status: "open",
  },
  {
    id: "finding-005",
    severity: "MEDIUM",
    title: "RDS Instance Publicly Accessible",
    resource: "postgres-prod-primary",
    resourceType: "RDS Instance",
    description: "RDS instance is marked as publicly accessible, which may expose the database to unauthorized access attempts.",
    remediation: "Disable public accessibility and use VPC security groups to control access.",
    category: "RDS",
    discoveredAt: new Date(Date.now() - 345600000).toISOString(),
    status: "open",
  },
  {
    id: "finding-006",
    severity: "LOW",
    title: "CloudTrail Log File Validation Disabled",
    resource: "main-trail",
    resourceType: "CloudTrail",
    description: "CloudTrail log file validation is disabled, making it harder to detect log tampering.",
    remediation: "Enable log file validation in CloudTrail settings.",
    category: "CloudTrail",
    discoveredAt: new Date(Date.now() - 432000000).toISOString(),
    status: "open",
  },
]

export const infrastructureData = {
  resources: [
    {
      id: "i-0a1b2c3d4e5f6g7h8",
      name: "web-server-prod-1",
      type: "EC2",
      provider: "AWS",
      region: "us-east-1",
      status: "running",
      healthScore: 85,
      criticalIssues: 2,
      highIssues: 3,
      mediumIssues: 5,
      lowIssues: 1,
      complianceScore: 78,
      tags: { Environment: "Production", Team: "Platform" },
      lastScanned: "2024-01-15T10:30:00Z",
      owner: "platform-team@example.com",
    },
    {
      id: "i-1b2c3d4e5f6g7h8i9",
      name: "api-server-prod-1",
      type: "EC2",
      provider: "AWS",
      region: "us-east-1",
      status: "running",
      healthScore: 92,
      criticalIssues: 0,
      highIssues: 1,
      mediumIssues: 2,
      lowIssues: 0,
      complianceScore: 95,
      tags: { Environment: "Production", Team: "Backend" },
      lastScanned: "2024-01-15T10:32:00Z",
      owner: "backend-team@example.com",
    },
    {
      id: "i-2c3d4e5f6g7h8i9j0",
      name: "batch-processor-1",
      type: "EC2",
      provider: "AWS",
      region: "us-west-2",
      status: "running",
      healthScore: 88,
      criticalIssues: 1,
      highIssues: 2,
      mediumIssues: 3,
      lowIssues: 2,
      complianceScore: 82,
      tags: { Environment: "Production", Team: "Data" },
      lastScanned: "2024-01-15T10:28:00Z",
      owner: "data-team@example.com",
    },
    {
      id: "i-3d4e5f6g7h8i9j0k1",
      name: "staging-app-server",
      type: "EC2",
      provider: "AWS",
      region: "us-east-1",
      status: "running",
      healthScore: 75,
      criticalIssues: 3,
      highIssues: 4,
      mediumIssues: 6,
      lowIssues: 3,
      complianceScore: 70,
      tags: { Environment: "Staging", Team: "Platform" },
      lastScanned: "2024-01-15T10:25:00Z",
      owner: "platform-team@example.com",
    },
    {
      id: "rds-postgres-prod-main",
      name: "postgres-prod-primary",
      type: "RDS",
      provider: "AWS",
      region: "us-east-1",
      status: "running",
      healthScore: 90,
      criticalIssues: 0,
      highIssues: 1,
      mediumIssues: 1,
      lowIssues: 0,
      complianceScore: 93,
      tags: { Environment: "Production", Team: "Database" },
      lastScanned: "2024-01-15T10:35:00Z",
      owner: "dba-team@example.com",
    },
  ],
  stats: {
    avgHealthScore: 78,
    healthScoreTrend: -3,
    needAttention: 4,
    totalIssues: 40,
    criticalIssues: 6,
    averageScore: 89,
    averageScoreTrend: 25,
    lastScanTime: "2 min ago",
  },
  infrastructure: {
    containerClusters: 0,
    kubernetesWorkloads: 0,
    standaloneVMs: 4,
    vmScalingGroups: 0,
    relationalDatabases: 1,
    blockStorage: 0,
    fileStorage: 0,
    objectStorage: 0,
  },
  securityIssues: {
    critical: 6,
    high: 11,
    medium: 17,
    low: 6,
    totalIssues: 40,
    todayChange: 43,
    cveCount: 4,
    threatsCount: 20,
    zeroDayCount: 11,
    secretsCount: 4,
    complianceCount: 9,
  },
  complianceSystems: [
    {
      name: "Payment-Prod",
      healthScore: 88,
      criticalGaps: 12,
      controlsCount: 200,
      owner: "Alex Kim",
      tags: ["Prod", "PCI DSS v4.0"],
    },
    {
      name: "Health-Records",
      healthScore: 84,
      criticalGaps: 18,
      controlsCount: 188,
      owner: "Dr. Sarah Johnson",
      tags: ["Prod", "HIPAA 2023"],
    },
    {
      name: "Data-Pipeline",
      healthScore: 89,
      criticalGaps: 154,
      controlsCount: 154,
      owner: "Sarah Chen",
      tags: ["Prod", "SOC 2 Type II"],
    },
    {
      name: "Auth-Service",
      healthScore: 86,
      criticalGaps: 117,
      controlsCount: 117,
      owner: "Michael Torres",
      tags: ["Prod", "ISO 27001:2022"],
    },
  ],
}
