#!/usr/bin/env python3
"""Record what the backend's Review producer declares, without executing it.

The frontend's Review tests should consume a fixture GENERATED by the backend
(the real executor plus the real ``RoleReviewDetailResult.model_dump``). That
generation has to run where pydantic is installed and where the backend repo
may be written to, which is the backend owner's side of the release boundary,
not this one.

Until that fixture exists, this records the part that CAN be read without
crossing the boundary or executing anything: the producer's declared field
sets and list caps, lifted out of the source with ``ast``, plus the hashes
Root needs to regenerate and compare against the final backend head.

    python scripts/derive-producer-contract.py --backend /path/to/saferemediate-backend

Read-only: it opens files and writes one JSON record here. It is NOT a
substitute for the generated fixture and does not contain a response body.
"""
from __future__ import annotations

import argparse
import ast
import hashlib
import json
import subprocess
from pathlib import Path

PRODUCER = Path("unified/decision/operations/iam_role_review_detail.py")
ROUTE = Path("api/iam_gap_analysis.py")
CONTRACT_TEST = Path("tests/decision/test_role_review_scope_contract.py")
OUT = Path(__file__).resolve().parent.parent / "__tests__" / "fixtures" / "iam-review" / "PRODUCER_CONTRACT.json"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _models(source: str) -> dict:
    out: dict = {}
    for node in ast.parse(source).body:
        if not isinstance(node, ast.ClassDef):
            continue
        fields = []
        for stmt in node.body:
            if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                cap = None
                if isinstance(stmt.value, ast.Call):
                    for kw in stmt.value.keywords:
                        if kw.arg == "max_length" and isinstance(kw.value, ast.Constant):
                            cap = kw.value.value
                fields.append({
                    "name": stmt.target.id,
                    "annotation": ast.unparse(stmt.annotation),
                    "max_length": cap,
                })
        if fields:
            out[node.name] = fields
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--backend", required=True, type=Path)
    args = ap.parse_args()
    be: Path = args.backend

    models = _models((be / PRODUCER).read_text())
    schema_hash = hashlib.sha256(json.dumps(models, sort_keys=True).encode()).hexdigest()
    def _git(*args: str) -> str:
        return subprocess.run(["git", "-C", str(be), *args],
                              capture_output=True, text=True, check=False).stdout.strip()

    head = _git("rev-parse", "HEAD")
    described = _git("describe", "--all", "--exact-match", head) or _git("name-rev", "--name-only", head)

    result = models["RoleReviewDetailResult"]
    record = {
        "__what_this_is__": (
            "A read-only record of the backend Review producer's DECLARED contract. "
            "It is not a response body and must not be used as one. The generated "
            "fixture it is waiting for is described under pending_fixture."
        ),
        "backend": {
            "head_sha": head or None,
            "read_from_ref": described or None,
            "note": (
                "Hashes are from the ref above. Compare against the backend head the "
                "release actually composes; if that head differs, regenerate this record "
                "rather than trusting these hashes."
            ),
            "sources": {
                str(PRODUCER): _sha256(be / PRODUCER),
                str(ROUTE): _sha256(be / ROUTE),
                str(CONTRACT_TEST): _sha256(be / CONTRACT_TEST),
            },
        },
        "schema_hash": schema_hash,
        "result_model": {
            "name": "RoleReviewDetailResult",
            "field_count": len(result),
            "fields": [f["name"] for f in result],
            "declared_list_caps": {f["name"]: f["max_length"] for f in result if f["max_length"] is not None},
        },
        "summary_model": {
            "name": "ReviewSummary",
            "fields": [f["name"] for f in models["ReviewSummary"]],
        },
        "route_query_params": ["days", "envelope", "customer_id", "account_id", "region"],
        "pending_fixture": {
            "status": "NOT GENERATED -- blocked at the release-ownership boundary",
            "why": (
                "Generating it means executing the real operation executor and "
                "RoleReviewDetailResult.model_dump, which needs pydantic. pydantic is "
                "not installed here and PyPI is unreachable from this session, and the "
                "backend repo is owned by the Semantic task, so it cannot be added there "
                "from here."
            ),
            "payload_sha256": None,
        },
        "derived_by": "saferemediate-frontend scripts/derive-producer-contract.py",
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n")
    print(f"wrote {OUT}")
    print(f"schema_hash {schema_hash}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
