#!/bin/bash
# SafeRemediate Demo - Complete Setup Script
# Run this once to set up everything for the demo

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEMO_DIR="$(dirname "$SCRIPT_DIR")"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}SafeRemediate Demo Setup${NC}"
echo -e "${BLUE}========================================${NC}"

# Check prerequisites
echo -e "\n${YELLOW}Checking prerequisites...${NC}"

check_command() {
    if command -v "$1" &> /dev/null; then
        echo -e "${GREEN}  ✓ $1 installed${NC}"
        return 0
    else
        echo -e "${RED}  ✗ $1 not found${NC}"
        return 1
    fi
}

MISSING=0
check_command "terraform" || MISSING=1
check_command "aws" || MISSING=1
check_command "curl" || MISSING=1
check_command "python3" || MISSING=1

if [ $MISSING -eq 1 ]; then
    echo -e "\n${RED}Please install missing prerequisites before continuing.${NC}"
    exit 1
fi

# Check AWS credentials
echo -e "\n${YELLOW}Checking AWS credentials...${NC}"
if aws sts get-caller-identity &> /dev/null; then
    ACCOUNT=$(aws sts get-caller-identity --query Account --output text)
    echo -e "${GREEN}  ✓ AWS credentials valid (Account: $ACCOUNT)${NC}"
else
    echo -e "${RED}  ✗ AWS credentials not configured${NC}"
    echo -e "    Run: aws configure"
    exit 1
fi

# Ask for confirmation
echo -e "\n${YELLOW}This will create AWS resources in your account.${NC}"
echo -e "Estimated cost: ~\$5-10/day (mostly NAT Gateway + RDS)"
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
fi

# Initialize and apply Terraform
echo -e "\n${BLUE}[1/4] Deploying infrastructure with Terraform...${NC}"
cd "$DEMO_DIR/terraform"

terraform init
terraform apply -auto-approve

# Get outputs
ALB_DNS=$(terraform output -raw alb_dns)
S3_BUCKET=$(terraform output -raw s3_bucket)
VPC_ID=$(terraform output -raw vpc_id)

echo -e "\n${GREEN}Infrastructure deployed!${NC}"
echo -e "  ALB DNS: $ALB_DNS"
echo -e "  S3 Bucket: $S3_BUCKET"
echo -e "  VPC ID: $VPC_ID"

# Wait for ALB to become healthy
echo -e "\n${BLUE}[2/4] Waiting for ALB to become healthy...${NC}"
echo "This may take 2-3 minutes..."

for i in {1..30}; do
    if curl -s -o /dev/null -w "%{http_code}" "http://$ALB_DNS/" | grep -q "200"; then
        echo -e "${GREEN}  ✓ ALB is healthy${NC}"
        break
    fi
    echo "  Waiting... ($i/30)"
    sleep 10
done

# Start traffic simulation
echo -e "\n${BLUE}[3/4] Starting initial traffic simulation...${NC}"
cd "$DEMO_DIR/scripts"
./simulate-traffic.sh

# Create .env file for frontend
echo -e "\n${BLUE}[4/4] Creating environment configuration...${NC}"
ENV_FILE="$(dirname "$DEMO_DIR")/.env.local"

cat > "$ENV_FILE" << EOF
# SafeRemediate Demo Configuration
# Generated by setup-demo.sh

# AWS Configuration
AWS_REGION=eu-west-1
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}

# Demo Infrastructure
DEMO_ALB_DNS=$ALB_DNS
DEMO_S3_BUCKET=$S3_BUCKET
DEMO_VPC_ID=$VPC_ID

# Backend URL (update if using different backend)
NEXT_PUBLIC_BACKEND_URL=https://saferemediate-backend.onrender.com
EOF

echo -e "${GREEN}  ✓ Environment file created: $ENV_FILE${NC}"

# Summary
echo -e "\n${GREEN}========================================${NC}"
echo -e "${GREEN}Demo Setup Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "Demo Infrastructure:"
echo -e "  ${BLUE}ALB URL:${NC} http://$ALB_DNS"
echo -e "  ${BLUE}S3 Bucket:${NC} $S3_BUCKET"
echo -e "  ${BLUE}VPC ID:${NC} $VPC_ID"
echo ""
echo -e "Security Issues Created (for demo):"
echo -e "  ${RED}✗${NC} SSH (22) open to 0.0.0.0/0 on web servers"
echo -e "  ${RED}✗${NC} RDP (3389) open to 0.0.0.0/0 on web servers"
echo -e "  ${RED}✗${NC} MySQL (3306) open to 0.0.0.0/0 on web servers"
echo -e "  ${RED}✗${NC} Overly permissive IAM roles (ec2:*, rds:*, etc)"
echo ""
echo -e "Next Steps:"
echo -e "  1. Start the frontend: ${YELLOW}npm run dev${NC}"
echo -e "  2. Open: ${YELLOW}http://localhost:3000${NC}"
echo -e "  3. Create system 'Payment-Prod' and tag resources"
echo -e "  4. Run continuous traffic: ${YELLOW}python3 demo-pack/scripts/continuous-traffic.py --alb-dns $ALB_DNS --s3-bucket $S3_BUCKET${NC}"
echo ""
echo -e "Cleanup when done:"
echo -e "  ${YELLOW}cd demo-pack/terraform && terraform destroy -auto-approve${NC}"
echo ""
